[package]
name = "rustzx"
version = "0.9.2"
authors = ["Vladislav Nikonov <pacmancoder@gmail.com>"]
publish = false
description = "ZX Spectum emulator"
repository = "https://github.com/pacmancoder/rustzx"
readme = "README.md"
keywords = ["emulator", "game", "z80"]
license = "MIT"

[dependencies]
lazy_static = "0.2"
clap = "2.9"

ayumi = { git = "https://github.com/pacmancoder/rust-ayumi.git"}

[dependencies.sdl2]
version = "^0.32.2"
features = ["unsafe_textures"]